import { Challenge, Badge, TrackQuestion } from "./types";

export const INITIAL_CHALLENGES: Challenge[] = [
  // ── Transport ──────────────────────────────────────────────────────────
  {
    id: "c1",
    title: "Walk 15 Minutes",
    category: "transport",
    description: "Ditch the vehicle and take a refreshing walk to the grocery store or work.",
    rewardXP: 100,
    difficulty: "Easy",
    impactText: "Saves 1.5 kg CO₂",
    completed: false,
    emoji: "🚶",
    co2Reward: 1.5,
    waterReward: 0,
    costReward: 20,
    timeEstimate: "15 min",
    isDaily: true,
  },
  {
    id: "c6",
    title: "Cycle to Work",
    category: "transport",
    description: "Swap your car for a bicycle commute. Great cardio and zero emissions!",
    rewardXP: 130,
    difficulty: "Medium",
    impactText: "Saves 3.2 kg CO₂",
    completed: false,
    emoji: "🚲",
    co2Reward: 3.2,
    waterReward: 0,
    costReward: 50,
    timeEstimate: "30 min",
    isDaily: true,
  },
  {
    id: "c7",
    title: "Carpool This Week",
    category: "transport",
    description: "Share your commute with a neighbour or colleague for the whole week.",
    rewardXP: 200,
    difficulty: "Hard",
    impactText: "Saves 8 kg CO₂",
    completed: false,
    emoji: "🚗",
    co2Reward: 8.0,
    waterReward: 0,
    costReward: 120,
    timeEstimate: "1 week",
    isDaily: false,
  },

  // ── Energy ─────────────────────────────────────────────────────────────
  {
    id: "c2",
    title: "Turn Off Unused Lights",
    category: "energy",
    description: "Do a quick home sweep and turn off any light bulbs or fans in empty rooms.",
    rewardXP: 80,
    difficulty: "Easy",
    impactText: "Saves 0.8 kg CO₂ & ₹15",
    completed: false,
    emoji: "💡",
    co2Reward: 0.8,
    waterReward: 0,
    costReward: 15,
    timeEstimate: "2 min",
    isDaily: true,
  },
  {
    id: "c8",
    title: "Unplug Vampire Devices",
    category: "energy",
    description: "Unplug chargers, TVs, and appliances that drain standby power overnight.",
    rewardXP: 90,
    difficulty: "Easy",
    impactText: "Saves 1.2 kg CO₂",
    completed: false,
    emoji: "🔌",
    co2Reward: 1.2,
    waterReward: 0,
    costReward: 30,
    timeEstimate: "5 min",
    isDaily: true,
  },
  {
    id: "c9",
    title: "AC at 24°C All Day",
    category: "energy",
    description: "Set your air conditioner to 24°C or higher for the entire day. Use fans to supplement.",
    rewardXP: 160,
    difficulty: "Medium",
    impactText: "Saves 2.5 kg CO₂ & ₹80",
    completed: false,
    emoji: "🌬️",
    co2Reward: 2.5,
    waterReward: 0,
    costReward: 80,
    timeEstimate: "All day",
    isDaily: true,
  },

  // ── Food ───────────────────────────────────────────────────────────────
  {
    id: "c3",
    title: "Take a 5-Min Shorter Shower",
    category: "food",
    description: "Speed up your shower ritual by setting a fast-tempo, upbeat song.",
    rewardXP: 120,
    difficulty: "Medium",
    impactText: "Saves 25 Liters of water!",
    completed: false,
    emoji: "🚿",
    co2Reward: 0.5,
    waterReward: 25,
    costReward: 10,
    timeEstimate: "5 min",
    isDaily: true,
  },
  {
    id: "c5",
    title: "Eco Meal Selection",
    category: "food",
    description: "Keep lunch or dinner completely meat-free. Choose green legumes and organic grains.",
    rewardXP: 150,
    difficulty: "Medium",
    impactText: "Saves 2 kg CO₂ and water!",
    completed: false,
    emoji: "🥗",
    co2Reward: 2.0,
    waterReward: 15,
    costReward: 40,
    timeEstimate: "1 meal",
    isDaily: true,
  },
  {
    id: "c10",
    title: "Zero Food Waste Day",
    category: "food",
    description: "Plan meals to use all ingredients. Compost any leftovers instead of throwing them away.",
    rewardXP: 180,
    difficulty: "Hard",
    impactText: "Saves 3 kg CO₂ & 20L water",
    completed: false,
    emoji: "🍽️",
    co2Reward: 3.0,
    waterReward: 20,
    costReward: 60,
    timeEstimate: "All day",
    isDaily: false,
  },

  // ── Shopping ───────────────────────────────────────────────────────────
  {
    id: "c4",
    title: "Avoid Plastic Bottles",
    category: "shopping",
    description: "Carry your trusty reusable flask today instead of purchasing single-use plastic water bottles.",
    rewardXP: 90,
    difficulty: "Easy",
    impactText: "Offsets plastic waste",
    completed: false,
    emoji: "🧴",
    co2Reward: 1.0,
    waterReward: 5,
    costReward: 30,
    timeEstimate: "All day",
    isDaily: true,
  },
  {
    id: "c11",
    title: "Buy Local Produce",
    category: "shopping",
    description: "Purchase fruits and vegetables from a local farmer's market instead of imported goods.",
    rewardXP: 110,
    difficulty: "Medium",
    impactText: "Saves 1.8 kg CO₂",
    completed: false,
    emoji: "🥬",
    co2Reward: 1.8,
    waterReward: 4,
    costReward: 10,
    timeEstimate: "30 min",
    isDaily: false,
  },
  {
    id: "c12",
    title: "Repair Don't Replace",
    category: "shopping",
    description: "Fix a torn garment, repair an appliance, or refurbish furniture instead of buying new.",
    rewardXP: 220,
    difficulty: "Hard",
    impactText: "Saves 5 kg CO₂ & ₹200",
    completed: false,
    emoji: "🧵",
    co2Reward: 5.0,
    waterReward: 15,
    costReward: 200,
    timeEstimate: "1 hour",
    isDaily: false,
  },

  // ── Community (NEW) ────────────────────────────────────────────────────
  {
    id: "c13",
    title: "Teach a Green Tip",
    category: "community",
    description: "Share one sustainability tip with a friend, family member, or coworker today.",
    rewardXP: 100,
    difficulty: "Easy",
    impactText: "Multiplied awareness!",
    completed: false,
    emoji: "🗣️",
    co2Reward: 0.5,
    waterReward: 0,
    costReward: 0,
    timeEstimate: "5 min",
    isDaily: true,
  },
  {
    id: "c14",
    title: "Neighbourhood Cleanup",
    category: "community",
    description: "Spend 20 minutes picking up litter in your local park, street, or community area.",
    rewardXP: 170,
    difficulty: "Medium",
    impactText: "Cleaner neighbourhood!",
    completed: false,
    emoji: "🧹",
    co2Reward: 0.3,
    waterReward: 0,
    costReward: 0,
    timeEstimate: "20 min",
    isDaily: false,
  },

  // ── Mindfulness (NEW) ──────────────────────────────────────────────────
  {
    id: "c15",
    title: "Nature Gratitude Walk",
    category: "mindfulness",
    description: "Take a 10-minute walk and notice 3 things in nature you're grateful for.",
    rewardXP: 80,
    difficulty: "Easy",
    impactText: "Mental clarity & joy",
    completed: false,
    emoji: "🌸",
    co2Reward: 0.2,
    waterReward: 0,
    costReward: 0,
    timeEstimate: "10 min",
    isDaily: true,
  },
  {
    id: "c16",
    title: "Digital Detox Hour",
    category: "mindfulness",
    description: "Spend one hour without screens. Read a book, garden, or simply breathe outdoors.",
    rewardXP: 140,
    difficulty: "Medium",
    impactText: "Saves device energy & calm",
    completed: false,
    emoji: "📵",
    co2Reward: 0.4,
    waterReward: 0,
    costReward: 5,
    timeEstimate: "1 hour",
    isDaily: false,
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: "b1",
    title: "Water Saver",
    description: "Save over 50 Liters of water in total through habit adjustments.",
    emoji: "💧",
    iconName: "water_drop",
    colorClass: "from-blue-400 to-blue-600",
    unlocked: false,
    requirement: "Save 50L Water",
  },
  {
    id: "b2",
    title: "Green Commuter",
    description: "Record 3 clean travel choices like walking or cycling.",
    emoji: "🚲",
    iconName: "directions_bike",
    colorClass: "from-green-400 to-emerald-600",
    unlocked: false,
    requirement: "Record 3 walk/cycle choices",
  },
  {
    id: "b3",
    title: "Energy Star",
    description: "Offset over 5 kg of CO₂ through smart home utility habits.",
    emoji: "⚡",
    iconName: "bolt",
    colorClass: "from-amber-400 to-orange-500",
    unlocked: false,
    requirement: "Offset 5 kg CO₂",
  },
  {
    id: "b4",
    title: "Forest Guardian",
    description: "Unlock by growing your digital forest to the 'Sapling' level (400 XP).",
    emoji: "🌲",
    iconName: "park",
    colorClass: "from-green-600 to-teal-800",
    unlocked: false,
    requirement: "Reach 400 XP",
  },
  {
    id: "b5",
    title: "Eco Conversationalist",
    description: "Have a helpful Q&A conversation with Sprout, your AI coach.",
    emoji: "💬",
    iconName: "chat",
    colorClass: "from-indigo-400 to-purple-600",
    unlocked: false,
    requirement: "Chat with the AI Coach",
  },
  {
    id: "b6",
    title: "Community Champion",
    description: "Complete 3 community challenges and inspire others around you.",
    emoji: "🤝",
    iconName: "people",
    colorClass: "from-pink-400 to-rose-600",
    unlocked: false,
    requirement: "Complete 3 community tasks",
  },
  {
    id: "b7",
    title: "Mindful Green",
    description: "Complete 2 mindfulness challenges to nurture your inner garden.",
    emoji: "🧘",
    iconName: "spa",
    colorClass: "from-purple-400 to-violet-600",
    unlocked: false,
    requirement: "Complete 2 mindfulness tasks",
  },
  {
    id: "b8",
    title: "Family Root",
    description: "Create or join a family group and grow together.",
    emoji: "👨‍👩‍👧‍👦",
    iconName: "family",
    colorClass: "from-teal-400 to-cyan-600",
    unlocked: false,
    requirement: "Join a family group",
  },
];

export const TRACKING_QUESTIONS: Record<string, TrackQuestion> = {
  transport: {
    id: "q_transport",
    question: "How did you travel today?",
    options: [
      {
        label: "Walked",
        description: "Zero fuel, pure physical strength. Great for your heart!",
        emoji: "🚶",
        co2Saved: 2.2,
        waterSaved: 0,
        costSaved: 40,
        xp: 40,
        feedback: "Wonderful choice! Walking keeps you fit, saves fuel costs, and results in exactly 0.0g carbon output. 🌱",
      },
      {
        label: "Bicycle",
        description: "Pedal power! Fast, carbon-free, and super fun.",
        emoji: "🚲",
        co2Saved: 2.0,
        waterSaved: 0,
        costSaved: 35,
        xp: 35,
        feedback: "Two wheels, zero carbon! You cleared the roads and boosted your energy today. Zoom zoom! 🚴‍♂️",
      },
      {
        label: "Bus or Train",
        description: "Sharing the journey with others. A great community choice.",
        emoji: "🚌",
        co2Saved: 1.4,
        waterSaved: 0,
        costSaved: 25,
        xp: 25,
        feedback: "Brilliant! Public transit significantly cuts per-person carbon emissions. That is shared impact! 🚌",
      },
      {
        label: "Car or Auto",
        description: "Individual motor trip. Think of carpooling next time!",
        emoji: "🚗",
        co2Saved: 0.2,
        waterSaved: 0,
        costSaved: 5,
        xp: 10,
        feedback: "Recorded. Traveling by car has a higher footprint, but you can try to group chores to offset of it next time! 🚗",
      }
    ]
  },
  food: {
    id: "q_food",
    question: "What best describes today's meals?",
    options: [
      {
        label: "Mostly Plant-Based",
        description: "Delectable veggies, lentils, legumes, tofu, fruit, and nuts.",
        emoji: "🥗",
        co2Saved: 2.5,
        waterSaved: 30,
        costSaved: 50,
        xp: 45,
        feedback: "Incredible feast! Plant-based meals require up to 90% less land and fresh water than meat. Your body says thank you! 🥦",
      },
      {
        label: "Mixed Meal",
        description: "A balanced menu featuring some dairy, eggs, or light poultry.",
        emoji: "🍲",
        co2Saved: 1.1,
        waterSaved: 10,
        costSaved: 15,
        xp: 20,
        feedback: "A nutritious, balanced approach. Adding more colorful plants will help multiply your forest XP score! 🌽",
      },
      {
        label: "Mostly Meat",
        description: "Beef, mutton, seafood, or chicken as the center plate.",
        emoji: "🥩",
        co2Saved: 0.1,
        waterSaved: 2,
        costSaved: -10,
        xp: 10,
        feedback: "Logged safely. Meat sourcing has a high water and methane footprint. How about simple plant lunches twice a week? 🍽️",
      }
    ]
  },
  energy: {
    id: "q_energy",
    question: "How did you conserve electricity today?",
    options: [
      {
        label: "Swept off Standby",
        description: "Turned off socket switches for chargers, microwaves, and TVs.",
        emoji: "🔌",
        co2Saved: 1.2,
        waterSaved: 0,
        costSaved: 30,
        xp: 30,
        feedback: "Spectacular sweep! 'Vampire energy' drain accounts for up to 10% of standard home utility bills. 🔌",
      },
      {
        label: "Air-Dried Clothes",
        description: "Avoided the hot laundry dryer. Used a sunny balcony or clothesline.",
        emoji: "👕",
        co2Saved: 1.8,
        waterSaved: 0,
        costSaved: 45,
        xp: 35,
        feedback: "Fresh breezes win! Hang-hanging clothes keeps them structural, smells organic, and saves massive heavy appliance power. 👕",
      },
      {
        label: "Natural Cooling",
        description: "Used open windows or set the cooling air conditioner to 24°C+.",
        emoji: "🌬️",
        co2Saved: 1.5,
        waterSaved: 0,
        costSaved: 50,
        xp: 30,
        feedback: "Perfect setting! Restricting heavy AC cooling offsets load pressures on local grids and lowers costs immediately. 🌬️",
      }
    ]
  },
  shopping: {
    id: "q_shopping",
    question: "What eco choice did you make while buying?",
    options: [
      {
        label: "Own Tote Bag",
        description: "Arrived prepared with cotton bags or fabric containers of your own.",
        emoji: "🛍️",
        co2Saved: 0.8,
        waterSaved: 2,
        costSaved: 15,
        xp: 25,
        feedback: "Zero-waste hero! Bags that are re-used prevent toxic ocean microplastics. You are keeping our coastlines pristine. 🛍️",
      },
      {
        label: "Organic & Regional",
        description: "Purchased locally grown apples, regional greens, or community bakery bread.",
        emoji: "🥬",
        co2Saved: 1.6,
        waterSaved: 4,
        costSaved: 10,
        xp: 30,
        feedback: "Fresh from the roots! Local buying bypasses 'food miles' and fuels independent farmers in your region. 🧑‍🌾",
      },
      {
        label: "Repaired Over Buying",
        description: "Stitched a tear, fixed an item, or simple recycling.",
        emoji: "🧵",
        co2Saved: 2.8,
        waterSaved: 15,
        costSaved: 150,
        xp: 40,
        feedback: "True warm minimalism. Circular restoration is the ultimate sustainability rule. Outstanding craft! 🩹",
      }
    ]
  }
};
